/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.VehicleInfo;
import Model.VehicleInfoHistory;
import java.util.Set;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.AbstractButton;

/**
 *
 * @author Krish
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VehicleInfoHistory history;

    public CreateJPanel(VehicleInfoHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAvail = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSN = new javax.swing.JLabel();
        lblMN = new javax.swing.JLabel();
        lblUber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblED = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        txtSN = new javax.swing.JTextField();
        txtMN = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtED = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        ckcBox = new javax.swing.JCheckBox();
        ckcBx1 = new javax.swing.JCheckBox();
        lblMax = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        lblerror2 = new javax.swing.JLabel();
        lblerrorTxt = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Vehicle Information");

        lblAvail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAvail.setText("Availability?");

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDate.setText("Date");

        lblCompany.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCompany.setText("Company");

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblYear.setText("Manufacturing Year");

        lblMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMin.setText("Minimum Seat");

        lblSN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSN.setText("Serial Number");

        lblMN.setText("Model Number");

        lblUber.setText("Uber Afiliation");

        lblCity.setText("City");

        lblED.setText("Expiry Date");

        txtED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEDActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMax.setText("Maximum Seat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCompany)
                                    .addComponent(lblDate)
                                    .addComponent(lblYear)
                                    .addComponent(lblAvail)
                                    .addComponent(lblSN)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblerror2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblerrorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMax, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMin, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ckcBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUber, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMN, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(txtSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMN, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtED, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckcBx1)))
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMN)
                        .addComponent(txtMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckcBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUber)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckcBx1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblED)
                    .addComponent(txtED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerror2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMax)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblerrorTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSN, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean error = false;
        String b = txtCompany.getText();
        if (b == null || b.equals("")) {
            JOptionPane.showMessageDialog(null, "Brand Can't be Empty!");
            error = true;
            return;
        }

        String model = txtMN.getText();

        if (model == null || model.equals("")) {
            JOptionPane.showMessageDialog(null, "Model Number Can't be Empty!");
            error = true;
            return;
        }

        String serial = txtSN.getText();

        try {
            Integer.parseInt(serial);
        } catch (NumberFormatException e) {
            error = true;
            JOptionPane.showMessageDialog(null, "Enter valid Serial Number");
            return;
        }

        String city1 = txtCity.getText();
        if (city1 == null || city1.equals("")) {
            JOptionPane.showMessageDialog(null, "City Can't be Empty!");
            error = true;
            return;
        }
        
        String date1 = txtDate.getText();
        try {
            Integer.parseInt(date1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Date cant be empty");
            error = true;
            return;
        }

        String year = txtYear.getText();
        try {
            Integer.parseInt(year);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter a valid Manufactured Year");
            error = true;
            return;
        }
        
        
        
        
        if (!error) {
            VehicleInfo vi = history.addNewInfo();
            boolean availability = ckcBox.isSelected();
            String date = txtDate.getText();
            String company = txtCompany.getText();
            String manufacturingYear = txtYear.getText();
            String MinimumSeat = txtMin.getText();
            if (!txtMin.getText().equals("") && Integer.parseInt(txtMin.getText()) >= 2) {
                vi.setMinSeat(MinimumSeat);
            } else {
                JOptionPane.showMessageDialog(this, "Minimum seat 2");
            }
// check if it is >=2
            String MaximumSeat = txtMax.getText();
            if (!txtMin.getText().equals("") && Integer.parseInt(txtMax.getText()) <= 8) {
                vi.setMaxSeat(MaximumSeat);

            } else {

                JOptionPane.showMessageDialog(this, "Maximum seat 8");
            }
//  check if it is <=8
            String serialNumber = txtSN.getText();
            String modelNumber = txtMN.getText();
            boolean uberCar = ckcBx1.isSelected();
            String city = txtCity.getText();
            String expirydate = txtED.getText();// TODO add your handling code here:

            vi.setDate(date);
            vi.setCompany(company);
            vi.setManufacturingYear(manufacturingYear);

            vi.setSerialNumber(serialNumber);
            vi.setModelNumber(modelNumber);
            vi.setUberCar(uberCar);
            Date lastUpdatedDate = new Date();
            vi.setLastUpdatedDate(String.valueOf(lastUpdatedDate));
            vi.setCity(city);
            vi.setExpirydate(expirydate);
            vi.setAvailability(availability);
            history.setUpDT(new Date());

            JOptionPane.showMessageDialog(this, "New Vehicle Information has been added!");
        }
        ckcBox.setSelected(false);
        txtDate.setText("");
        txtCompany.setText("");
        txtYear.setText("");
        txtMin.setText("");
        txtMax.setText("");
        txtSN.setText("");
        txtMN.setText("");
        ckcBx1.setSelected(false);
        txtCity.setText("");
        txtED.setText("");


    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox ckcBox;
    private javax.swing.JCheckBox ckcBx1;
    private javax.swing.JLabel lblAvail;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblED;
    private javax.swing.JLabel lblMN;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUber;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblerror2;
    private javax.swing.JLabel lblerrorTxt;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtED;
    private javax.swing.JTextField txtMN;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtSN;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
