/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.PHouse;
import Model.Person;
import Model.PersonInfoHistory;
import com.sun.org.apache.bcel.internal.generic.Select;
import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Krish
 */
public class AddJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddJPanel
     */
    Person person;
    PersonInfoHistory PersonInfoHistory;

    public AddJPanel(PersonInfoHistory history) {
        initComponents();
        this.PersonInfoHistory = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPID = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPID = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        cbxCity = new javax.swing.JComboBox<>();
        lblCommunity = new javax.swing.JLabel();
        cBcCom = new javax.swing.JComboBox<>();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtZip = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblAddress2 = new javax.swing.JLabel();
        txtAddress2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cBcHouse = new javax.swing.JComboBox<>();

        lblHeading.setBackground(new java.awt.Color(255, 204, 204));
        lblHeading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(204, 51, 0));
        lblHeading.setText("ADD PERSON DETAILS");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name :");

        lblPID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPID.setText("ID Number:");

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAge.setText("Age:");

        lblContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContact.setText("Contact :");

        txtPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIDActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(102, 51, 255));
        lblCity.setText("City");

        cbxCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Boston" }));
        cbxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCityActionPerformed(evt);
            }
        });

        lblCommunity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCommunity.setForeground(new java.awt.Color(102, 153, 255));
        lblCommunity.setText("Cummunity");

        cBcCom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cBcCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cBcCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBcComActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address Line 1:");

        lblAddress1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress1.setText("Zip Code:");

        btnSave.setBackground(new java.awt.Color(255, 204, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 153, 153));
        btnSave.setText("SAVE!");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblAddress2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress2.setText("Address Line 2:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("House no.");

        cBcHouse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cBcHouse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        cBcHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBcHouseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCommunity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBcCom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddress1)
                            .addComponent(lblAddress2)
                            .addComponent(lblAge)
                            .addComponent(lblName)
                            .addComponent(lblContact)
                            .addComponent(lblPID)
                            .addComponent(lblAddress))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtPID)
                            .addComponent(txtAge)
                            .addComponent(txtContact)
                            .addComponent(txtAddress)
                            .addComponent(txtAddress2)
                            .addComponent(txtZip))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBcHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(lblHeading)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cBcHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBcCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPIDActionPerformed

    public static boolean isValidInputInfo(String inputInfo, String regex) {

        Pattern pattern = Pattern.compile(regex);

        Matcher match = pattern.matcher(inputInfo);

        return match.matches();

    }

    public void validateInputInfo(Person person) {
        boolean error = false;
        boolean validInputInfo = isValidInputInfo(person.getPersonNm(), "^[aA-zZ]{2,10}$");
        //System.out.println(validInputInfo);
        if (!validInputInfo) {
            JOptionPane.showMessageDialog(this, "Invalid Data");
            PersonInfoHistory.remove(person);
            error = true;
        }
        boolean validInputInfo2 = isValidInputInfo(String.valueOf(person.getContactNo()), "/[6-9][1-9]{9}");

        if (!validInputInfo2) {
            JOptionPane.showMessageDialog(this, "Invalid Phone Number");
            PersonInfoHistory.remove(person);
            error = true;
        }
        
        
              

        if (!error) {
            saveDetails();
        }
    }

    private void saveDetails() throws HeadlessException {
        JOptionPane.showMessageDialog(this, "Person Information Saved");

        txtName.setText("");
        txtPID.setText("");
        txtAge.setText("");
        txtContact.setText("");
        txtAddress.setText("");
        txtAddress2.setText("");
        txtZip.setText("");
        cBcHouse.setSelectedIndex(0);
        cbxCity.setSelectedIndex(0);
        cBcCom.setSelectedIndex(0);
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean error = false;

        String city = cbxCity.getSelectedItem().toString();

        if (city.equals("Select")) {
            JOptionPane.showMessageDialog(null, "First step is to select City");

            error = true;
            return;
        }

        String community = cBcCom.getSelectedItem().toString();
        if (community.equals("Select")) {
            JOptionPane.showMessageDialog(null, "Dont forget Community!");

            error = true;
            return;
        }

        String name = txtName.getText();
        if (name == null || name.equals("")) {

            JOptionPane.showMessageDialog(null, "Name Can not be Empty");

            error = true;
            return;
        }

        String pID = txtPID.getText();

        if (pID == null || pID.equals("")) {

            JOptionPane.showMessageDialog(null, "Add ID");

            error = true;
            return;
        }

        String age = txtAge.getText();

        if (age == null || age.equals("")) {

            JOptionPane.showMessageDialog(null, "Add Age");

            error = true;
            return;
        }

        String contact = txtContact.getText();

        if (contact == null || contact.equals("")) {

            JOptionPane.showMessageDialog(null, "Add Contact");

            error = true;
            return;
        }

        String adl1 = txtAddress.getText();

        if (adl1 == null || adl1.equals("")) {

            JOptionPane.showMessageDialog(null, "Add complete Address");

            error = true;
            return;
        }

        String perhouse = cBcHouse.getSelectedItem().toString();
        if (perhouse.equals("")) {
            JOptionPane.showMessageDialog(null, "House no. is mandatory!");

            error = true;
            return;
        }

        if (!error) {

            Person newPerson = PersonInfoHistory.addPerson();
            newPerson.setPersonNm(txtName.getText());
            newPerson.setPersonID(txtPID.getText());
            newPerson.setAge(Integer.parseInt(txtAge.getText()));
            newPerson.setContactNo(Integer.parseInt(txtContact.getText()));
            PHouse house = new PHouse();
            house.setAddressln1(txtAddress.getText());
            house.setAddressln2(txtAddress2.getText());
            house.setPinCode(Integer.parseInt(txtZip.getText()));
            house.setResidenceNumber(Integer.parseInt((String) cBcHouse.getSelectedItem()));
            house.setCityNm(cbxCity.getSelectedItem().toString());
            house.setCommunityNm(cBcCom.getSelectedItem().toString());
            newPerson.setHouse(house);
            validateInputInfo(newPerson);


    }//GEN-LAST:event_btnSaveActionPerformed

    }

    private void cBcComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBcComActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        if (cBcCom.getSelectedItem().toString() == "Serene") {
            model.addElement("1");
            model.addElement("2");
            model.addElement("3");

    }//GEN-LAST:event_cBcComActionPerformed
    
        else if (cBcCom.getSelectedItem().toString() == "Solace") {
            model.addElement("1");
            model.addElement("2");
            model.addElement("3");
        }

        cBcHouse.setModel(model);

    }
    private void cbxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCityActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        model.addElement("Select");
        model.addElement("Serene");
        model.addElement("Solace");

        cBcCom.setModel(model);

    }//GEN-LAST:event_cbxCityActionPerformed

    private void cBcHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBcHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBcHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cBcCom;
    private javax.swing.JComboBox<String> cBcHouse;
    private javax.swing.JComboBox<String> cbxCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
