/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.PEncounter;
import Model.PEncounterHistory;
import Model.PatientInfo;
import Model.PatientInfoHistory;
import Model.Person;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Krish
 */
public class SearchJPanel extends javax.swing.JPanel {
    Person personID;
PEncounterHistory pEncounterHistory;
        PatientInfoHistory patientInfoHistory;
        String selectplace = "";
    /**
     * Creates new form SearchJPanel
     */
    public SearchJPanel(PEncounterHistory pEncounterHistory, PatientInfoHistory patientInfoHistory) {
        
       initComponents();
       
       this.pEncounterHistory = pEncounterHistory;
       this.patientInfoHistory = patientInfoHistory;
       displaypEncounterHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblpEncounter = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cBcfAge = new javax.swing.JComboBox<>();
        txtAge1 = new javax.swing.JTextField();
        txtAge2 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpEncounter2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tblpEncounter.setBackground(new java.awt.Color(255, 153, 153));
        tblpEncounter.setForeground(new java.awt.Color(255, 102, 102));
        tblpEncounter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PatientID", "Status(Normal/Abnormal)", "Blood Pressure", "Visit Date and time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpEncounter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpEncounterMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpEncounter);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("PATIENT HISTORY");

        cBcfAge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Find By ", "Age", "Community" }));
        cBcfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBcfAgeActionPerformed(evt);
            }
        });

        txtAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge1ActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblpEncounter2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PatientID", "Name", "Community", "City", "Age", "Patient is Normal", "Residence no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpEncounter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpEncounter2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpEncounter2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Please select Range if Finding by Age");

        jLabel3.setText("Range 1");

        jLabel4.setText("Range 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSearch)
                                            .addComponent(txtAge2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(411, 411, 411))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cBcfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBcfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblpEncounterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpEncounterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpEncounterMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        ArrayList<PatientInfo> phl = patientInfoHistory.getPatientInfoHistory();
        
        
        if(selectplace == "Age")
        {
        
            int minAge = Integer.parseInt(txtAge1.getText());
            int maxAge = Integer.parseInt(txtAge2.getText());
            List<PatientInfo> newP = phl.stream().filter(a -> a.getAge()>=minAge && a.isPatientIsNormal() == false).collect(Collectors.toList());
            
            viewPatientTable(newP);
        }
        else if(selectplace == "Community")
        {
            String cName = txtAge1.getText();
            List<PatientInfo> newP = phl.stream().filter(a -> a.getHouse().getCommunityNm().contains(cName) && a.isPatientIsNormal()== false).collect(Collectors.toList());
            viewPatientTable(newP);
            
            
    }//GEN-LAST:event_btnSearchActionPerformed

    
    }
    private void txtAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1ActionPerformed

    private void tblpEncounter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpEncounter2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpEncounter2MouseClicked

    private void cBcfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBcfAgeActionPerformed
        // TODO add your handling code here:
        selectplace = cBcfAge.getSelectedItem().toString();
    }//GEN-LAST:event_cBcfAgeActionPerformed

    
    private void displaypEncounterHistory() {
DefaultTableModel model = (DefaultTableModel) tblpEncounter.getModel();
model.setRowCount(0);

for (PEncounter pe : pEncounterHistory.getEncounterList()){
Object[] row = new Object [4];
System.out.println(pe.getpID());
row[0] = pe.getpID().getPersonID();
//    System.out.println(pe.getpID());
row[1] = pe.isPatientIsNormal()? "Normal" : "Not normal";
row[2] = pe.getVits().getBp();
row[3] = pe.getDateStamp();
model.addRow(row);

}
        
//To change body of generated methods, choose Tools | Templates.
    }

private void viewPatientTable(List<PatientInfo> plist){
    
    DefaultTableModel model = (DefaultTableModel) tblpEncounter2.getModel();
    model.setRowCount(0);
    for(PatientInfo pi : plist ){
    
    Object[] row = new Object[7];
    
    row[0] = pi.getPersonID();
    row[1] = pi.getPersonNm();
    row[2] = pi.getHouse().getCommunityNm();
    row[3] = pi.getHouse().getCityNm();
    row[4] = pi.getAge();
    row[5] = pi.isPatientIsNormal();
    row[6]= pi.getHouse().getResidenceNumber();
    model.addRow(row);
    }
    
    




}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cBcfAge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblpEncounter;
    private javax.swing.JTable tblpEncounter2;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtAge2;
    // End of variables declaration//GEN-END:variables
}
